---
- name: Create working directory
  file:
    path: "{{ aar_working_dir }}"
    state: directory

- name: Copy website file template
  template:
    src: "{{ aar_index_file }}"
    dest: "{{ aar_working_dir }}/index.html"